blog/urls.py
from django.urls import path    
from blog.views import blog_view ,blog_single, blog_category , blog_search


app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('<int:pid>',blog_single, name='single'),
    path('category/<str:cat_name>',blog_category , name='category'),
    path('author/<str:author_username>',blog_view, name = 'author'),
    path('search/',blog_search, name ='search'),
    path('tag/<str:tag_name>/', blog_view, name='tag')

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap 
from robots.views import RuleList

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),     #Summernote
    path('captcha/', include('captcha.urls')),                  #captcha config url
    path('accounts/', include('accounts.urls')),                #Accounts App url
     path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),  #Sitemap
    path("robots.txt", RuleList.as_view(), name="robots"),      #robot SEO url
    #Password_reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

handler404 = 'website.views.custom_404'
handler500 = 'website.views.custom_500'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path    
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index , name='index'),
    path('contact',contact , name='contact'),
    path('about',about , name='about'),
    path('newsletter', Newsletter_view , name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse                                                 #sitemap absolute settings
from taggit.managers import TaggableManager                                     #taggit for manage Tags

class Category(models.Model):
        name = models.CharField(max_length=255)
        def __str__(self):
            return self.name
        
class Post(models.Model):
    image =models.ImageField(upload_to='blog/',default='blog/blog-2.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE ,null=True)        #authorیک کلید فرعی واسطه به یوزر
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()                                                     #taggit for manage Tags
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    login_required = models.BooleanField(default=False)                          #login requirments in posts

    class Meta:
        ordering = ['created_date']
    def __str__(self):
        return self.title
    
    #sitemap absolute settings
    def get_absolute_url(self):
         return reverse('blog:single', kwargs={'pid': self.id})

blog/views.py
from django.shortcuts import render ,get_object_or_404
from blog.models import Post
from django.utils import timezone
from django.core.paginator  import Paginator ,EmptyPage ,PageNotAnInteger
from taggit.models import Tag


def blog_view(request, author_username=None, **kwargs):
    current_time = timezone.now()  
    posts = Post.objects.filter(published_date__lte=current_time, status=1).order_by('-published_date')

    if author_username:
        posts = posts.filter(author__username=author_username)

    if kwargs.get('tag_name') is not None:
        # Use filter instead of Post.filter
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
        
    all_tags = Tag.objects.all()

    # Pagination (next-previous page)
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    

    context = {'posts': posts, 'all_tags': all_tags}
    return render(request, 'blog/blog.html', context)
    

def blog_single(request, pid):
    current_time = timezone.now() 
    all_posts = Post.objects.all()
     #status=1 فقط به منتشر شده ها دسترسی نمایش میده
     #get_object_or_404 :  یعنی اگر نبود پیام 404 
    post = get_object_or_404(all_posts, pk=pid, status=1 ,published_date__lte=current_time)
    #هر با دیده شود یکی اضافه کند
    post.counted_views += 1
    post.save()

    prev_post = all_posts.filter(pk__lt=pid,status=1).last()
    next_post = all_posts.filter(pk__gt=pid,status=1).first()

    all_tags = Tag.objects.all()

    context = {
        'post': post,
        'prev_post': prev_post,
        'next_post': next_post,
        'all_tags': all_tags,
    }
    return render(request,'blog/blog-single.html',context)

#make url for categories
def blog_category(request, cat_name):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts':posts}
    return render(request,'blog/categories-posts.html',context)

#SEARCH function
def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        posts = posts.filter(content__contains = request.GET.get('s'))
    context = {'posts':posts}
    return render(request,'blog/blog.html',context)

templates/blog/blog-search.html
{%load static%}
<div class="col-lg-4">

    <div class="sidebar">

      <h3 class="sidebar-title">Search</h3>
      <div class="sidebar-item search-form">
        <form action="{% url 'blog:search'%}" method="get">
          <input placeholder="Search in contents" name="s" type="text">
          <button type="submit"><i class="bi bi-search"></i></button>
        </form>
      </div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{%load static%}
{%load custom_tags%}
{% block title %}blog-single{% endblock %}

{% block content %}

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Blog Single</h2>
        <ol>
          <li><a href="{% url 'website:index' %}">Home</a></li>
          <li><a href="{% url 'blog:index' %}">Blog</a></li>
          <li>Blog Single</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Blog Single Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row">

        <div class="col-lg-8 entries">

          <article class="entry entry-single">

            <div class="entry-img">
              <img src="{{ post.image.url }}" alt="post-image" class="img-fluid">
            </div>

            <h2 class="entry-title">
              <a href="{% url 'blog:single' pid=post.id  %}">{{post.title}}</a>
            </h2>

            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                    href="blog-single.html">{{post.author}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                    href="blog-single.html"><time>{{post.published_date|date:"D d M"}}</time></a></li>
                <li class="d-flex align-items-center"><i></i> <a href="#">Counted Views: {{post.counted_views}}</a></li>
              </ul>
            </div>

            <div class="entry-content">
              {{post.content}}
            </div>

            <div class="entry-footer">
              <i class="bi bi-folder"></i>
              <ul class="cats">
                {%for cat in post.category.all%}
                <li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}} ,</a></li>
                {%endfor%}
              </ul>

              <i class="bi bi-tags">
                {% for tag in post.tags.all %}
                <a>{{ tag.name }}</a>
                {% endfor %}
              </i>

            </div>

            <!--paginator buttons-->
            <div class="entry-footer"></div>
            <div class="entry-footer"></div>
            <div class="navigation-area">
              <div class="row">

                <!-- Previous Post Button -->


                <style>
               .btn-primary {
                  background-color: rgba(77, 109, 151, 0.993);
                  color: white; 
                }
                </style>

                {% if prev_post %}
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                  <div class="navigation-button">
                    <a href="{% url 'blog:single' prev_post.pk %}" class="btn btn-primary">Prev Post</a>
                  </div>
                </div>
                {% endif %}

                <!-- Next Post Button -->
                {% if next_post %}
                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                  <div class="navigation-button">
                    <a href="{% url 'blog:single' next_post.pk %}" class="btn btn-primary">Next Post</a>
                  </div>
                </div>
                {% endif %}
              </div>
            </div>
           

            <!--paginator details-->
            <div class="navigation-area">
              <div class="row">


                <style>
                  .thumb img {
                    width: 100px;
                    height: 60px;
                    border-radius: 10px;
                    margin-top: 10px;
                  }
                </style>


                {% if prev_post %}
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">

                  <div class="thumb">
                    {% if prev_post %}
                    <a href="{% url 'blog:single' prev_post.pk  %}">
                      {%endif%}
                      <img class="img-fluid" src="{{ prev_post.image.url }}" alt="post">
                    </a>
                    <p>{{ prev_post.title|limit_words_with_ellipsis:1}}</p>
                  </div>
                  <div class="arrow">
                    {% if prev_post %}
                    <a href="{% url 'blog:single' prev_post.pk  %}">
                      {%endif%}
                      <span class="lnr text-white lnr-arrow-left"></span>
                    </a>
      
                  </div>

                  <div class="read-more">

                    
                    {% if prev_post %}
                    <a href="{% url 'blog:single' prev_post.pk  %}">
                      {%endif%}
                      <h4></h4>
                    </a>
                  </div>

                </div>
                {%endif%}

                {% if next_post %}
                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">

                  <div class="detials">
                    
                    {% if next_post %}
                    <a href="{% url 'blog:single' next_post.pk  %}">
                      {%endif%}
                      <h4></h4>
                    </a>
                    
                  </div>
                  <div class="arrow">
                    {% if next_post %}
                    <a href="{% url 'blog:single' next_post.pk  %}">
                      {%endif%}
                      <span class="lnr text-white lnr-arrow-right"></span></a>
                  </div>


                  <div class="thumb">
                    {% if next_post %}
                    <a href="{% url 'blog:single' next_post.pk  %}">
                      {%endif%}
                      <img class="img-fluid" src="{{ next_post.image.url }}" alt="post"></a>
                      <p>{{ next_post.title|limit_words_with_ellipsis:1}}</p>
                  </div>
                  
                </div>
                {%endif%}
              </div>
            </div>

            <!--end ofpaginator-->
          </article>
          <!--Commenting system-->

          <div id="disqus_thread"></div>
          <script>
            /**
            *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
            *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
            /*
            var disqus_config = function () {
            this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };
            */
            (function () { // DON'T EDIT BELOW THIS LINE
              var d = document, s = d.createElement('script');
              s.src = 'https://mycv-2.disqus.com/embed.js';
              s.setAttribute('data-timestamp', +new Date());
              (d.head || d.body).appendChild(s);
            })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
              Disqus.</a></noscript>

          <!-- End blog comments -->

        </div>
        <!-- End blog entries list -->

        {% search_bar %}

        <!-- End sidebar search formn-->

        {% postcategories %}

        <!-- End sidebar categories-->
        <div>
          {% latestpost %}
        </div>
        <!-- End sidebar recent posts-->
        <!-- End sidebar tags-->

      </div><!-- End sidebar -->

    </div><!-- End blog sidebar -->

    </div>

    </div>
  </section><!-- End Blog Single Section -->

</main><!-- End #main -->

{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{%load static%}
{% load custom_tags %}
{% block title %}blog{% endblock %}
{% load humanize %}
{% block content %}
<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Blog</h2>
        <ol>
          <li><a href="{% url 'website:index' %}">Home</a></li>
          <li>Blog</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row">

        <div class="col-lg-8 entries">
          {{post}}
          {%for post in posts%}
          <article class="entry">

            <div class="entry-img">
              <img src="{{ post.image.url }}" alt="post" class="img-fluid">
            </div>

            <h2 class="entry-title">
              <a href="{% url 'blog:single' pid=post.id  %}">{{post.title}}</a>
            </h2>

            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">
                    {{post.author}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                    href="@"><time>{{post.published_date|naturaltime}}</time></a></li>
                <li class="d-flex align-items-center"><i></i> <a href="#">
                    Counted Views: {{post.counted_views}}</a></li>
                {% for cat in post.category.all %}
                <li class="d-flex align-items-center"><i></i> <a
                    href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>
                {% endfor %}
              </ul>
            </div>

            <div class="entry-content">

              {{post.content|limit_words_with_ellipsis:11}}

              <div class="read-more">
                <a href="/blog{{post.id}}">Read More</a>
              </div>
            </div>

          </article>
          {% endfor %}
          <!-- End blog entry -->

          <div class="blog-pagination">
            <ul class="justify-content-center">
              {% for i in posts.paginator.page_range %}
              <li><a href="?page={{i}}">{{i}}</a></li>
              {% endfor %}
            </ul>
          </div>

        </div><!-- End blog entries list -->

        {% search_bar %}


        <!-- End sidebar search formn-->

        {% postcategories %}

        <!-- End sidebar categories-->
        <div>
          {% latestpost %}
        </div>
        <!-- End sidebar recent posts-->
        <h3 class="sidebar-title">Tags</h3>
        <div class="sidebar-item tags">
          <ul>
            {% for tag in all_tags %}
            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>

            {% endfor %}
          </ul>
        </div>

      </div><!-- End sidebar -->

    </div><!-- End blog sidebar -->

    </div>

    </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->

{% endblock %}

templates/blog/categories-posts.html
{%load static%}
{%load custom_tags%}


<h3 class="sidebar-title">Categories</h3>
<div class="sidebar-item categories">
  <ul>
    {% for name,count in categories.items %}
    <li><a href="#">{{name}}<span>({{count}})</span></a></li>
    {% endfor %}
  </ul>
</div>

templates/blog/latest-posts.html
{%load static%}

<h3 class="sidebar-title">Last Posts</h3>
<div class="sidebar-item recent-posts">
    {% for post in posts %}
    <div class="post-item clearfix">
        <img src="{{post.image.url}}" alt="post">
        <h4><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h4>
        <time >{{post.published_date|date:"d M y"}}</time>
    </div>
    {%endfor%}
</div>

templates/blog/tagged_posts.html
{% load static %}

<h3 class="sidebar-title">Tags</h3>
<div class="sidebar-item tags">
  <ul>
    {% for tag in posts.tags.all %}
    <li><a href="#">{{tag.name}}</a></li>
    {% endfor %}

  </ul>
</div>