accounts/urls.py
from django.urls import path    
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('signup',views.signup_view,name='signup'),
    
]

blog/urls.py
from django.urls import path    
from blog.views import blog_view ,blog_single, blog_category , blog_search


app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('<int:pid>',blog_single, name='single'),
    path('category/<str:cat_name>',blog_category , name='category'),
    path('author/<str:author_username>',blog_view, name = 'author'),
    path('search/',blog_search, name ='search'),
    path('tag/<str:tag_name>/', blog_view, name='tag')

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap 
from robots.views import RuleList

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),     #Summernote
    path('captcha/', include('captcha.urls')),                  #captcha config url
    path('accounts/', include('accounts.urls')),                #Accounts App url
     path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),  #Sitemap
    path("robots.txt", RuleList.as_view(), name="robots"),      #robot SEO url
    #Password_reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

handler404 = 'website.views.custom_404'
handler500 = 'website.views.custom_500'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path    
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index , name='index'),
    path('contact',contact , name='contact'),
    path('about',about , name='about'),
    path('newsletter', Newsletter_view , name='newsletter'),
]

templates/about.html
{% extends 'base.html' %}
{%load static%}
{% block title %}about{% endblock %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>About</h2>
          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li>About</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= About Us Section ======= -->
    <section id="about-us" class="about-us">
      <div class="container">

        <div class="row no-gutters">
          <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start" data-aos="fade-right"></div>
          <div class="col-xl-7 ps-0 ps-lg-5 pe-lg-1 d-flex align-items-stretch">
            <div class="content d-flex flex-column justify-content-center">
              <h3 data-aos="fade-up">Exceptional Teaching Team</h3>
              <p data-aos="fade-up">
                "Our teachers at News Reporter Academy are the epitome of excellence. With vast industry experience, dedication, and expertise, they empower students to excel in the field of journalism."
              </p>
              <div class="row">
                <div class="col-md-6 icon-box" data-aos="fade-up">
                  <i class="bx bx-receipt"></i>
                  <h4>Editing and Proofreading</h4>
                  <p>Learn the art of editing, fact-checking, and ensuring the accuracy and clarity of articles.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-cube-alt"></i>
                  <h4>Media Ethics and Law</h4>
                  <p>Understand the ethical standards and legal aspects of journalism, including libel, copyright, and privacy.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                  <i class="bx bx-images"></i>
                  <h4>Digital Journalism</h4>
                  <p>Embrace the digital age by mastering online platforms, multimedia storytelling, and social media for news dissemination.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                  <i class="bx bx-receipt"></i>
                  <h4>Feature Writing</h4>
                  <p>Hone your skills in writing engaging feature articles, profiles, and human-interest stories.</p>
                </div>
              </div>
            </div><!-- End .content-->
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->

    <!-- ======= Our Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Our <strong>Teachers</strong></h2>
          <p>Our teachers epitomize excellence, bringing a wealth of knowledge, experience, and dedication to the classroom. Their high-level expertise enriches our educational environment, inspiring students to reach new heights and ensuring our institution remains a beacon of quality education.</p>
        </div>

        <div class="row">

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                <img src="{% static 'img/team/team-1.jpg' %}" class="img-fluid" alt="team">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Walter White</h4>
                
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                <img src="{% static 'img/team/team-2.jpg' %}" class="img-fluid" alt="team">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Sarah Jhonson</h4>
              
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="200">
              <div class="member-img">
                <img src="{% static 'img/team/team-3.jpg' %}" class="img-fluid" alt="team">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>William Anderson</h4>
                
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="300">
              <div class="member-img">
                <img src="{% static 'img/team/team-4.jpg' %}" class="img-fluid" alt="team">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Amanda Jepson</h4>
               
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Our Team Section -->

    <!-- ======= Our Skills Section ======= -->
    <section id="skills" class="skills">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Our <strong>Features</strong></h2>
          <p>Our academy offers a comprehensive array of features to enhance the learning experience. These include a seasoned faculty, diverse course selection, state-of-the-art facilities, a thriving alumni network, and robust career support. However, we strive to address any potential drawbacks, ensuring affordability and accessibility for all aspiring learners.</p>
        </div>

        <div class="row skills-content">

          <div class="col-lg-6" data-aos="fade-up">

            <div class="progress">
              <span class="skill">Experienced Faculty<i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Diverse Course Offerings<i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">State-of-the-Art Facilities<i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

          </div>

          <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">

            <div class="progress">
              <span class="skill">Strong Alumni Network<i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Career Support Services <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">High Tuition Costs <i class="val">0%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

          </div>

        </div>

      </div>
    </section><!-- End Our Skills Section -->

  </main><!-- End #main -->

  {% endblock %}

templates/base.html
{% load static %}
{% load compress %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}</title>
    <meta content="Learn how to become a successful reporter with our digital news reporting academy. Get hands-on training in journalism, writing, and reporting skills. Start your journey in journalism today!" name="description">
    <meta content="digital news reporting, journalism training, reporter academy, journalism courses, reporting skills, journalism classes, news writing, journalism education" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/favicon.png' %}" rel="touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    {% compress css %}
    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    {% endcompress %}

    <!-- Template Main CSS File -->
    {% compress css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endcompress %}
    <!-- =======================================================
        ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                
                    {% if request.user.is_authenticated %}
                    <i><a href="#">Logged in as {{ request.user.username }}</a></i>
                    <i><a> | </a></i>
                    <i><a href="{% url 'accounts:logout' %}">Logout</a></i>
                    {% else %}
                    <i><a href="{% url 'accounts:login' %}">Login</a></i>
                    <i><a> | </a></i>
                    <i><a href="{% url 'accounts:signup' %}">Signup</a></i>
                    {% endif %}

        </div>
    </section>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex justify-content-between">

            <div class="logo">
                <h1 class="text-light"><a href="{% url 'website:index' %}">Smartworks Academy</h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a href="#"></a></li>
                    <li><a href="{% url 'website:index' %}">Home</a></li>
                    <li><a href="{% url 'website:about' %}">About</a></li>
                    <li><a href="{% url 'blog:index' %}">Blog</a></li>
                    <li><a href="{% url 'website:contact' %}">Contact</a></li>
                </ul>

            </nav><!-- .navbar -->

        </div>
    </header>
    <!-- End Header -->


    <!--======Content======-->
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>


    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>Smartworks</h3>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> smartworks@gmail.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:index' %}">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:about' %}">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:contact' %}">Contact us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'blog:index' %}">Blog</a></li>

                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>account</h4>
                        <ul>
                            {% if request.user.is_authenticated %}
                            <li><i class="bx bx-chevron-right"><a href="#">Logged in as {{ request.user.username }}</a></i></li> 
                            
                            <li><i class="bx bx-chevron-right"><a href="{% url 'accounts:logout' %}">Logout</a></i></li>
                            {% else %}
                            <li><i class="bx bx-chevron-right"><a href="{% url 'accounts:login' %}">Login</a></i></li>
                            
                            <li><i class="bx bx-chevron-right"><a href="{% url 'accounts:signup' %}">Signup</a></i></li>
                            {% endif %}


                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Join Our Newsletter</h4>
                        <p>please add your email here to join our community</p>
                        <form action="{% url 'website:newsletter' %}" method="post">
                            {% csrf_token %}
                            <input type="email" name="email" placeholder="Email Address"><input type="submit"
                                value="Subscribe">
                        </form>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>Kasra Torabi</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    
                    Designed by <a href="#">Kasra Torabi</a>
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    {% compress js %}
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
    {% endcompress %}
    <script id="dsq-count-scr" src="//mycv-2.disqus.com/count.js" async></script>

    <!-- Template Main JS File -->
    {% compress js %}
    <script src="{% static 'js/main.js' %}"></script>
    {% endcompress %}

</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{%load static%}
{% block title %}contact{% endblock %}

{% block content %}


<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Contact</h2>
        <ol>
          <li><a href="{% url 'website:index' %}">Home</a></li>
          <li>Contact</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Contact Section ======= -->
  <div class="map-section">
    <iframe style="border:0; width: 100%; height: 350px;"
      src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
      frameborder="0" allowfullscreen></iframe>
  </div>

  <section id="contact" class="contact">
    <div class="container">

      <div class="row justify-content-center" data-aos="fade-up">

        <div class="col-lg-10">

          <div class="info-wrap">
            <div class="row">
              <div class="col-lg-4 info">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>A108 Adam Street<br>New York, NY 535022</p>
              </div>

              <div class="col-lg-4 info mt-4 mt-lg-0">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>smartworks@gmail.com</p>
              </div>

              <div class="col-lg-4 info mt-4 mt-lg-0">
                <i class="bi bi-phone"></i>
                <h4>Call:</h4>
                <p>+1 5589 55488 51<br>+1 5589 22475 14</p>
              </div>
            </div>
          </div>

        </div>

      </div>

      <div class="row mt-5 justify-content-center" data-aos="fade-up">
        <div class="col-lg-10">
          <form action="{% url 'website:contact' %}" method="POST" id="contact-form" >
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="subject" placeholder="Subject">
            </div>
            <div class="form-group mt-3">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
            </div>
            <div class="mt-3">
              {{form.captcha}}
            </div>
            <div class="my-3">
              <div class="text-center"><button type="submit" class="orange-button">Send Message</button></div>
              {% if messages %}
              <ul class="sent-message">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
                {% if form.errors %}
                <div class="alert alert-danger">
                  <strong>Error:</strong> Please check your form fields.
                </div>
                {% endif %}
              {% endif %}
               </ul>
          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

</main><!-- End #main -->

{% endblock %}